services:
  cvmake:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: CV
    environment:
      POSTGRES_PASSWORD: 55555
      POSTGRES_DB: CV
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: MyRedis
    ports:
      - "6379:6379"

volumes:
  postgres_data: