services:
  cvmake:
    build: ./
    ports:
      - "-:8443:8443"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: CV
    environment:
      POSTGRES_PASSWORD: 63455
      POSTGRES_DB: CV
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: MyRedis
    ports:
      - "6377:6379"

volumes:
  postgres_data: